# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-39erXIELp-CIcnl_wqrSzJE-NHC37yL
"""

from fastapi import FastAPI
from recommender import recommend_songs

app = FastAPI(title="AI Song Recommendation API")

@app.get("/")
def home():
    return {"status": "API running"}

@app.get("/recommend")
def recommend(song: str, top_n: int = 10):
    return recommend_songs(song, top_n)